version: '3.9'

services:
  go:
    container_name: go
    image: golang:1.17-alpine
    restart: unless-stopped
    command: "tail -f /dev/null"
    volumes:
      - type: bind
        source: ./
        target: /app
    working_dir: /app
